pallets/blueprints/contact/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms_components import EmailField
from wtforms.validators import Length, DataRequired


class ContactForm(FlaskForm):
    email = EmailField(
        "What's your e-mail address", [DataRequired(), Length(3, 254)])
    message = TextAreaField(
        "What's is you question issue", [DataRequired(), Length(1, 7999)])

pallets/app.py
from flask import Flask
from pallets.core.configs import configs
from pallets.core.blueprints import blueprints
from pallets.core.extensions import extensions


CELERY_TASK_LIST = ['pallets.blueprints.contact.tasks']


def create_app(settings_override=None):
    """
        Create application by using factory pattern.
        :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)

    # Config
    configs(app, settings_override)

    # Blueprints
    blueprints(app)

    # Extensions
    extensions(app)

    return app

pallets/blueprints/contact/__init__.py
from pallets.blueprints.contact.views import contact

pallets/blueprints/contact/views.py
from flask import Blueprint, flash, redirect, request, url_for, render_template, current_app
from pallets.blueprints.contact.forms import ContactForm
from pallets.blueprints.contact.tasks import deliver_contact_email


contact = Blueprint("contact", __name__, template_folder="templates")


@contact.route("/contact", methods=["GET", "POST"])
def index():
    form = ContactForm()

    if form.validate_on_submit():

        # Run background
        deliver_contact_email.submit(
            mail_from=request.form.get("email"),
            mail_to=current_app.config.get("MAIL_USERNAME"),
            message=request.form.get("message"),
        )

        flash("Thanks, expect a response shortly", "success")
        return redirect(url_for("contact.index"))

    return render_template("index.j2", form=form)

pallets/blueprints/page/__init__.py
from pallets.blueprints.page.views import page

pallets/blueprints/page/views.py
from flask import Blueprint, render_template


page = Blueprint("page", __name__, template_folder="templates")


@page.route("/")
def home():
    return render_template("home.j2")


@page.route("/terms")
def terms():
    return render_template("terms.j2")


@page.route("/privacy")
def privacy():
    return render_template("privacy.j2")

pallets/core/blueprints.py
from flask import Flask
from pallets.blueprints.page import page
from pallets.blueprints.contact import contact


def blueprints(app: Flask):
    """
        Register the blueprint (mutates the app passing in).

        :params: Flask app instance
        :return: None
    """
    app.register_blueprint(page)
    app.register_blueprint(contact)

pallets/templates/layouts/base.j2
{% import 'macros/flash.j2' as flash with context %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}"
    />
    <script
      src="https://code.jquery.com/jquery-1.12.2.min.js"
      integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#navbar"
            aria-expanded="false"
            aria-controls="navbar"
          >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"> </span>
          </button>
          <a href="{{ url_for('page.home') }}">
            <h2>Pallets</h2>
          </a>
        </div>
    </div>
</nav>

<main class="container">
    {{ flash.render() }}

    <div class="md-margin-top">{% block heading %}{% endblock %}</div>
    {% block body %}{% endblock %}
</main>

<footer class="footer text-center">
    <div class="container">
        <ul class="list-inline">
            <li class="text-muted">Pallets &copy; 2021</li>
            <li><a href="{{ url_for('contact.index') }}">Contact</a></li>
            <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
            <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
        </ul>
    </div>
</footer>

<script
        src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
</script>
</body>
</html>

pallets/templates/macros/flash.j2
{# Render Flask messages. #}
{%- macro render() -%}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div id="flash-messages" class="row sm-margin-top">
                {% for category, msg in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ msg }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{%- endmacro -%}

pallets/templates/macros/form.j2
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(f) -%}
    <label for="{{ f.id }}">
        {%- if f.flags.required -%}
            <strong>{{ f.label.text }}</strong>
        {%- else %}
            {{ f.label.text }}
        {%- endif %}
    </label>
{%- endmacro -%}


{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
    {% if f.errors %}
        <ul class="list-unstyled text-danger field-error">
            {% for error in f.errors %}
                <li>{{ error | e }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{%- endmacro -%}


{# Render a form field. #}
{%- macro field(f, css_class='form-control') -%}
    {{ f(class=css_class, **kwargs) }}
{%- endmacro -%}


{# Render a checkbox field. #}
{%- macro checkbox_field(f) -%}
    {{ f(type='checkbox', **kwargs) }} {{ f.label }}
{%- endmacro -%}


{# Render a form group with errors for various field types. #}
{%- macro form_group(f, css_class='') -%}
    {% if f.errors %}
        {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
    {% endif %}

    {% if f.type == 'BooleanField' %}
        <div class="checkbox {{ css_class }}">
        {{ checkbox_field(f, **kwargs) }}
    {% else %}
        <div class="form-group {{ css_class }}">
        {{ field_label(f) }}
        {{ field(f, **kwargs) }}
    {% endif %}

{{ field_errors(f) }}
{{ caller () }}
</div>
{%- endmacro %}


{# Render a form tag that contains a CSRF token and all hidden fields. #}
{%- macro form_tag(endpoint, fid='', css_class='', method='post') -%}
    <form action="{{ url_for(endpoint, **kwargs) }}" method="{{ method }}"
          id="{{ fid }}" class="{{ css_class }}" role="form">
        {{ form.hidden_tag() }}
        {{ caller () }}
    </form>
{%- endmacro -%}